#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <cmath>
IDWVoiceMIDIStudioAudioProcessor::IDWVoiceMIDIStudioAudioProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::mono(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),apvts(*this,nullptr,"IDW_V7",layout()),presets(apvts){}
juce::AudioProcessorValueTreeState::ParameterLayout IDWVoiceMIDIStudioAudioProcessor::layout(){using F=juce::AudioParameterFloat;using I=juce::AudioParameterInt;using B=juce::AudioParameterBool;juce::AudioProcessorValueTreeState::ParameterLayout p;
p.add(std::make_unique<F>("gate","Gate",.001f,.2f,.008f));p.add(std::make_unique<F>("confidence","Confidence",.5f,1.f,.75f));p.add(std::make_unique<I>("bend","Bend",1,24,2));p.add(std::make_unique<B>("scaleLock","Scale Lock",false));p.add(std::make_unique<I>("root","Root",0,11,0));p.add(std::make_unique<I>("scaleMask","Scale Mask",1,4095,2741));
p.add(std::make_unique<B>("beatbox","Beatbox",true));p.add(std::make_unique<F>("beatThreshold","Beat Threshold",.005f,.2f,.035f));p.add(std::make_unique<I>("kick","Kick",0,127,36));p.add(std::make_unique<I>("snare","Snare",0,127,38));p.add(std::make_unique<I>("hat","Hat",0,127,42));
p.add(std::make_unique<B>("gestureCC","Gesture CC",true));p.add(std::make_unique<I>("cc","CC",0,127,74));p.add(std::make_unique<F>("ccSense","CC Sense",.25f,3.f,1.f));p.add(std::make_unique<B>("mpe","MPE",false));p.add(std::make_unique<I>("mpeFirst","MPE First",2,16,2));p.add(std::make_unique<I>("mpeLast","MPE Last",2,16,16));p.add(std::make_unique<I>("latencyMs","Latency",0,100,0));return p;}
void IDWVoiceMIDIStudioAudioProcessor::prepareToPlay(double s,int b){pitch.prepare(s,b);beats.prepare(s);mpe.reset();active=-1;silent=0;lastHz=0;}
void IDWVoiceMIDIStudioAudioProcessor::releaseResources(){pitch.reset();}
bool IDWVoiceMIDIStudioAudioProcessor::isBusesLayoutSupported(const BusesLayout&l)const{return l.getMainInputChannelSet()==juce::AudioChannelSet::mono();}
void IDWVoiceMIDIStudioAudioProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&o){juce::MidiBuffer incoming=o;learn.process(incoming,apvts);o.clear();int N=b.getNumSamples();auto*x=b.getReadPointer(0);
float h=pitch.process(x,N),r=pitch.rms(),q=pitch.confidence();freq=h;confidence=q;scale.setMask((uint16_t)apvts.getRawParameterValue("scaleMask")->load());mpe.setZone((int)apvts.getRawParameterValue("mpeFirst")->load(),(int)apvts.getRawParameterValue("mpeLast")->load());
bool mpeOn=apvts.getRawParameterValue("mpe")->load()>.5f;if(h>0&&r>=apvts.getRawParameterValue("gate")->load()&&q>=apvts.getRawParameterValue("confidence")->load()){float raw=69+12*std::log2(h/440.f);int n=(int)std::lround(raw);
if(apvts.getRawParameterValue("scaleLock")->load()>.5f)n=scale.quantize(n,(int)apvts.getRawParameterValue("root")->load());if(n!=active){if(active>=0){int c=mpeOn?mpe.channelFor(active):1;o.addEvent(juce::MidiMessage::noteOff(c,active),0);mpe.release(active);}
int c=mpeOn?mpe.allocate(n):1;o.addEvent(juce::MidiMessage::noteOn(c,n,(juce::uint8)100),0);active=n;}midi=n;silent=0;int c=mpeOn?mpe.channelFor(n):1,range=(int)apvts.getRawParameterValue("bend")->load();
o.addEvent(juce::MidiMessage::pitchWheel(c,juce::MidiMessage::pitchbendToPitchwheelPos(raw-std::round(raw),(float)range)),0);if(apvts.getRawParameterValue("gestureCC")->load()>.5f&&lastHz>0){float d=std::abs(12.f*std::log2(h/lastHz));int v=juce::jlimit(0,127,(int)(d*64*apvts.getRawParameterValue("ccSense")->load()));o.addEvent(juce::MidiMessage::controllerEvent(c,(int)apvts.getRawParameterValue("cc")->load(),v),0);}lastHz=h;}
else if(++silent>5&&active>=0){int c=mpeOn?mpe.channelFor(active):1;o.addEvent(juce::MidiMessage::noteOff(c,active),0);mpe.release(active);active=-1;midi=-1;}
auto k=apvts.getRawParameterValue("beatbox")->load()>.5f?beats.process(x,N,apvts.getRawParameterValue("beatThreshold")->load()):BeatboxClassifier::None;if(k){const char*id=k==BeatboxClassifier::Kick?"kick":k==BeatboxClassifier::Snare?"snare":"hat";int n=(int)apvts.getRawParameterValue(id)->load();o.addEvent(juce::MidiMessage::noteOn(10,n,(juce::uint8)115),0);o.addEvent(juce::MidiMessage::noteOff(10,n),juce::jmin(N-1,10));}
for(int c=1;c<b.getNumChannels();c++)b.copyFrom(c,0,b,0,0,N);}
juce::AudioProcessorEditor* IDWVoiceMIDIStudioAudioProcessor::createEditor(){return new IDWVoiceMIDIStudioAudioProcessorEditor(*this);}
void IDWVoiceMIDIStudioAudioProcessor::getStateInformation(juce::MemoryBlock&d){auto s=apvts.copyState();std::unique_ptr<juce::XmlElement>x(s.createXml());copyXmlToBinary(*x,d);}
void IDWVoiceMIDIStudioAudioProcessor::setStateInformation(const void*d,int n){std::unique_ptr<juce::XmlElement>x(getXmlFromBinary(d,n));if(x&&x->hasTagName(apvts.state.getType()))apvts.replaceState(juce::ValueTree::fromXml(*x));}
juce::AudioProcessor*JUCE_CALLTYPE createPluginFilter(){return new IDWVoiceMIDIStudioAudioProcessor();}
